AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Extract Predict Part 1 - Corporate Windows instance Resource deployment
        Parameters:
          - KeyName
          - VPC
          - Subnet
          - SecurityGroupIds
          - LatestWindowsAmiId
    ParameterLabels:
      VpcCIDR:
        default: Which VPC should this be deployed to?
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the file server
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.
  VPC:
    Description: VPC to deploy resources into
    Type: 'AWS::EC2::VPC::Id'
  Subnet:
    Description: Subnet to deploy resources into
    Type: 'AWS::EC2::Subnet::Id'
  SecurityGroupIds:
    Description: Specify the security group/s for resources
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
  LatestWindowsAmiId:
    Description: Do Not modify the below default value!
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: /aws/service/ami-windows-latest/Windows_Server-2019-English-Full-Base
Resources:
  WindowsInstanceRole:
    Type: 'AWS::IAM::Role'
    DeletionPolicy: Delete
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
  WindowsInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref WindowsInstanceRole
  WindowsInstanceRolePolicy:
    Type: 'AWS::IAM::Policy'
    DeletionPolicy: Delete
    Properties:
      PolicyName: !Sub 'Windows-client-${AWS::StackName}' # Check if works
      Roles:
        - !Ref WindowsInstanceRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:Get*'
              - 's3:List*'
            Resource: '*'
  WindowsInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref LatestWindowsAmiId
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      SecurityGroupIds: !Ref SecurityGroupIds
      SubnetId: !Ref Subnet
      IamInstanceProfile: !Ref WindowsInstanceProfile
      Tags:
        - Key: Name
          Value: DE-Extract-Windows-Instance
Outputs:
  WindowsInstance:
    Description: Private IP address of the newly created Windows EC2 instance
    Value: !GetAtt
      - WindowsInstance
      - PublicIp
